# Ein GitHub Workflow der bei jedem Push l채uft in dem wir nach den Begriffen:
#       password, passcode, Passwort,
# suchen.

name: Passwort Suche

# Controls when the workflow will run
on:
   
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    Password_Check:

        runs-on: ubuntu-latest

        steps:
            # Checkout
            - name: checkout
              id: checkout
              uses: actions/checkout@v3

            
            # Hier werden erstmal all die _vba Ordner rausgesucht
            - name: VBA Ordner suche
              id: ordnerSuche
              run: |
                find . -type d -name "*_vba" > vbaDirectories.txt
              shell: bash

            # Pr채ambel
            - name: Setup
              id: Setup
              run: |
                phrase="password"
                echo "Hier suchen wir innerhalb der _vba Ordner nach dem String '$phrase'."
                vbaDirectories=$(cat vbaDirectories.txt)
                rm -f vbaDirectories.txt
                echo $vbaDirectories

            # Hier suchen wir innerhalb der _vba Ordner nach dem String 'passwort'.
            - name: passwort scan
              id: passwort
              run: |
                # Loop through the list of "_vba" directories and scan files for "password"
                touch passwordFiles.txt
                for vbaDirectory in $vbaDirectories; do
                    echo "Der Ordner '$vbaDirectory' wird gepr체ft."
                    grep -Rnwl $vbaDirectory -e $phrase |            
                        while read -r file; do
                            echo "Die Datei '$file' enth채lt den String '$phrase'"
                            echo "$file" >> passwordFiles.txt
                        done
                done
                if [ -s passwordFiles.txt ] ; then
                    echo "Diese Dateien enthalten den String '$phrase':"
                    cat passwordFiles.txt
                    rm  -f passwordFiles.txt
                    exit 1
                else
                    echo "Keine Dateien enthalten den String '$phrase'."
                    rm  -f passwordFiles.txt 
                    exit 0
                fi
              shell: bash