# Ein GitHub Workflow der bei jedem Push läuft in dem wir nach den Begriffen:
#       password, passcode, Passwort,
# suchen.

name: Passwort Suche

# Controls when the workflow will run
on:
   
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    Password_Check:

        runs-on: ubuntu-latest

        steps:
            # Checkout
            - name: checkout
              id: checkout
              uses: actions/checkout@v3

            
            # Hier werden erstmal all die _vba Ordner rausgesucht
            - name: VBA Ordner suche
              id: ordnerSuche
              run: |
                find . -type d -name "*_vba" > vbaDirectories.txt
                cat vbaDirectories.txt
              shell: bash


            # Hier suchen wir innerhalb der _vba Ordner nach dem String 'passwort'.
            - name: passwort scan
              id: passwort
              run: |
                echo "Hier suchen wir innerhalb der _vba Ordner nach dem String 'passwort'."
                vbaDirectories=$(cat vbaDirectories.txt)
                echo $vbaDirectories

                # Loop through the list of "_vba" directories and scan files for "password"
                touch passwordFiles.txt
                for vbaDirectory in $vbaDirectories; do
                    echo "In the for-loop checking directory: '$vbaDirectory'"
                    grep -Rnwl $vbaDirectory -e 'password' |
                    while read -r file; do
                        echo "The file '$file' contains the phrase password"
                        echo "$file" >> passwordFiles.txt
                    done
                done
                if [ -s passwordFiles.txt ] ; then
                    echo "These are the files that contain the phrase 'password':"
                    cat passwordFiles.txt
                    exit 1
                fi
                exit 0
              shell: bash