# Ein GitHub Workflow der bei jedem Push läuft in dem wir nach den Begriffen:
#       password, passcode, Passwort,
# suchen.

name: Passwort Suche

# Controls when the workflow will run
on:
   
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    PHRASE: "password"

jobs:
    Password_Check:

        runs-on: ubuntu-latest

        steps:
            # Checkout
            - name: checkout
              id: checkout
              uses: actions/checkout@v3

            
            # Hier werden erstmal all die _vba Ordner rausgesucht
            - name: VBA Ordner suche
              id: ordnerSuche
              run: |
                find . -type d -name "*_vba" > vbaDirectories.txt
              shell: bash

            # Präambel
            - name: Setup
              id: Setup
              run: |
                echo "Hier suchen wir innerhalb der _vba Ordner nach dem String ' $PHRASE '."
                

            # Hier suchen wir innerhalb der _vba Ordner nach dem String in phrase.
            - name: passwort scan
              id: passwort
              run: |
                vbaDirectories=$(cat vbaDirectories.txt)
                rm -f vbaDirectories.txt
                echo $vbaDirectories
                # Loop through the list of "_vba" directories and scan files for "password"
                touch passwordFiles.txt
                for vbaDirectory in $vbaDirectories; do
                    echo "Der Ordner '$vbaDirectory' wird geprüft."
                    grep -Rnwl $vbaDirectory -e $PHRASE |            
                    while read -r file; do
                        echo "$file" >> passwordFiles.txt
                    done || true
                done
              shell: bash

            # Hier findet die Auswertung der Suche statt.
            - name: Results
              id: results
              run: |
                if [ -s passwordFiles.txt ] ; then
                    echo "Diese Dateien enthalten den String ' $PHRASE ':"
                    cat passwordFiles.txt
                    rm  -f passwordFiles.txt
                    exit 1
                else
                    echo "Keine Dateien enthalten den String ' $PHRASE '."
                    rm  -f passwordFiles.txt 
                    exit 0
                fi
              shell: bash