# Ein GitHub Workflow der bei jedem Push läuft in dem wir nach den Begriffen:
#       password, passcode, Passwort, etc
# suchen.

name: Passwort Suche

# Controls when the workflow will run
on:
   
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

#env:
#    PHRASE: "password\|Passwort\|pwd\|passcode\|Passcode\|Password\|passwort\|pwt"

jobs:
    Password_Check:

        runs-on: ubuntu-latest

        steps:
            # Checkout
            - name: checkout
              id: checkout
              uses: actions/checkout@v3
            
            # Hier werden erstmal all die _vba Ordner rausgesucht
            - name: VBA Ordner suche
              id: ordnerSuche
              run: |
                find . -type d -name "*_vba" > vbaDirectories.txt
                #cat vbaDirectories.txt
              shell: bash

            # Hier suchen wir innerhalb der _vba Ordner nach dem String in phrase.
            - name: passwort scan
              id: passwort
              run: |
                vbaDirectories=$(cat vbaDirectories.txt)
                rm -f vbaDirectories.txt
                #echo $vbaDirectories
                # Loop through the list of "_vba" directories and scan files for "password"
                
                
                #echo "Looking for $phrase ."
                for vbaDirectory in $vbaDirectories; do
                  #echo "in $vbaDirectory"
                  # A command looking for common variations of variables that might contain hardcoded passwords.
                  grep -rle '.*\(password\|Passwort\|pwd\|passcode\|Passcode\|Password\|passwort\|pwt\).*=.*\".*\"' "$vbaDirectory" >> passwordFiles.log            
                        
                        
                  grep -rle  '\(Protect\|Unprotect\) \".*\"' "$vbaDirectory" >> protectUnprotect.log 
                done

                
                if [ -e passwordFiles.log ] ; then
                    echo "Diese Dateien enthalten auffällige Begriffe."
                    cat passwordFiles.log
                    rm  -f passwordFiles.log
                    exit 1
                else
                    echo "Keine Dateien enthalten auffällige Strings."
                    rm  -f passwordFiles.log 
                    exit 0
                fi

                if [ -e protectUnprotect.log ] ; then
                    echo "Diese Dateien enthalten auffällige Begriffe."
                    cat protectUnprotect.log
                    rm  -f protectUnprotect.log
                    exit 1
                else
                    echo "Keine Dateien enthalten auffällige Strings."
                    rm  -f protectUnprotect.log 
                    exit 0
                fi
                
              shell: bash