name: VBA Scan Workflow
on: 
 workflow_dispatch:

jobs:
  Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
       path: target
    
    - name: My Action
      # here we specify which repository we want to call the code from
      # with the syntax: owner/repo@branch
      uses: benosul/SomeTests@main
      # Put an example of your mandatory inputs here
      with:
        reportType: 'User'
        dirPath: 'target'

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
       name: Report
       path: report.txt
