# Der Primäre GitHub Workflow der später mal die Workbooks mittels signtool.exe signieren soll

name: Signieren

# Controls when the workflow will run
on:
   
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    Signieren:

        runs-on: windows-latest

        steps:
            # In diesem Job soll dann signtool.exe und die benötigte Software installiert werden
            - name: Install Windows SDK
              run: |
                $sdkPath = Get-Command vswhere | ForEach-Object { $_.Source -replace '\\vswhere\.exe' }
                Add-Content -Path $env:GITHUB_PATH -Value "$sdkPath\VC\Auxiliary\Build\vcvars64.bat"


            # Hier wird das Signierskript eingefügt
            - name: signieren
              id: signieren
              run: |
                echo "Hier werden dann die gewünschten Dateien signiert."
                #signtool sign /v /td sha256 /fd sha256 /sha1 $Thumbprint $a
                # Run vcvarsall.bat to set up the environment
                cmd /c "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64

                # Add the location of signtool to the PATH
                $env:PATH = $env:PATH + ";" + "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.19041.0\x64"

                # Verify signtool is in the PATH
                where.exe signtool

    Git_Setup:
        
        runs-on: windows-latest

        steps:

          - name: Init
            shell: bash
            run: |
              ls -a
              git status
              git branch -a