# Der Primäre GitHub Workflow der später mal die Workbooks mittels signtool.exe signieren soll

name: Signieren

# Controls when the workflow will run
on:
   
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    Signieren:

        runs-on: windows-latest
        

        steps:

            # In diesem Job soll dann signtool.exe und die benötigte Software installiert/gefunden werden
            - name: Install Windows SDK

              run: |
                $sdkPath = Get-Command vswhere | ForEach-Object { $_.Source -replace '\\vswhere\.exe' }
                Add-Content -Path $env:GITHUB_PATH -Value "$sdkPath\VC\Auxiliary\Build\vcvars64.bat"

            
            - name: Certificate Setup
              env: 
                CERTIFICATE_CONTENT: ${{ secrets.TESTSECRET_CMDLINE}}
              run: |
                echo "$CERTIFICATE_CONTENT" > certificate.pfx

            # Hier wird das Signierskript eingefügt.
            - name: signieren
              id: signieren
              run: |
                echo "Hier werden dann die gewünschten Dateien signiert."
                #signtool sign /v /td sha256 /fd sha256 /sha1 $Thumbprint $a
                # Run vcvarsall.bat to set up the environment
                cmd /c "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64

                # Add the location of signtool to the PATH
                $env:PATH = $env:PATH + ";" + "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.19041.0\x64"

                # Verify signtool is in the PATH
                where.exe signtool

                signtool sign /a /fd SHA256 "CommitAddIn - Copy.xlsm"

            - name: GitSetup
              shell: bash
              run: |
                git config --global user.email "benjamin.osullivan@d-fine.com"
                git config --global user.name "Ben O'Sullivan"

            - name: Git Execute
              shell: bash
              run: |
                git add "CommitAddIn - Copy.xlsm"
                git commit -m "Commit from runner"
                git push

    Git_Setup:
        
        runs-on: windows-latest

        steps:

          # Checkout
          - name: checkout
            id: checkout
            uses: actions/checkout@v3

          - name: Init
            shell: bash
            run: |
              git branch -a

          - name: FindPath
            shell: bash
            run: pwd

#          - name: New file
#            shell: bash
#            run: echo "A file created on a remote runner" > remoteFile.txt

#          - name: commit and push
#            shell: bash
#            run: |
#              git add remoteFile.txt
#              git commit -m "A remote file creation/alteration"
#              git push