# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  signatureCheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up gpg to check for my signature
      - name: Configure gpg
        run: gpg --import ./TemporaryPublicKey.asc

      # Check files that should be signed for my signature
      - name: Check for the signature
        run: |
          for xlsmFile in "."/*.xlsm; do
            echo $xlsmFile
            gpgFile="${xlsmFile}.gpg"
            gpg --verify "$gpgFile"
          done 
          for dir in $(find . -type d -name "*_vba"); do
            echo "In directory $dir"
            for baseFile in "$dir"/*; do
              if [[ ! "$baseFile" =~ \.gpg$ ]]; then
                echo "Checking $baseFile"
                gpgFile="${baseFile}.gpg"
                echo $gpgFile
                gpg --verify $gpgFile
              fi
            done
          done

  passwordCheck:
    runs-on: ubuntu-latest
    needs: signatureCheck
    steps:
      - uses: actions/checkout@v3

      # Find all folders marked named "*_vba"
      - name: Find _vba Directories
        id: find-vba-dirs
        run: |
          find . -type d -name "*_vba" > vbaDirectories.txt
          #echo "name = vbaDirectories.txt" >> $GITHUB_OUTPUT
          cat vbaDirectories.txt
        shell: bash

      # Search for instances of "password" in the _vba directories
      - name: Scan _vba Directories
        id: scan
        run: |
          vbaDirectories=$(cat vbaDirectories.txt)
          echo "These are all _vba directories: " $vbaDirectories

          # Loop through the list of "_vba" directories and scan files for "password"
          touch passwordFiles.txt
          for vbaDirectory in $vbaDirectories; do
            echo "In the for loop"
            grep -Rnwl $vbaDirectory -e 'password' | while read -r file; do
                echo "The file '$file' contains the phrase password"
                echo "$file" >> passwordFiles.txt
              done || true
          done

          # If there are files containing the phrase password or Password return them 
          # and kill the workflow
          cat passwordFiles.txt
          if [ -s passwordFiles.txt ] ; then
            echo "There are files that contain the phrase password"
            cat passwordFiles.txt
            exit 1
          else
            echo "There are no vba-Module files that contain the phrase password"
            exit 0
          fi

        shell: bash
